spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    spring:

    security:
      user:
        name: admin
        password: 1234

